// Arrays
//--------------------------------------------------------------------------------------
 
var CONSOLEMSG = {
	0: "Invalid instruction. Type [help] for a list of available commands.\r\n",
	2: "Welcome to the FireSuite terminal. This is the FireSuite help manpage. For now, the terminal can run javascript commands. To initiate a prompt, type js:" 
};

var TRACERMSG = {
	0: "\r\n[*] Network tracer started. \r\n",
	1: "\r\n[*] Network tracer stopped by user.\r\n",
	2: "\r\n[*] Network tracer failed to load, sorry.\r\n",
	3: "\r\n[*] Type -help for commands."
};


var HTML = {
	1: {reg: '/MAX_FILE_SIZE(.*)VALUE=(.*)>/',impact:'MAX_FILE_SIZE should not be set clientside'},
	2: {reg: '/type=(.*)hidden(.*)>/',impact:'Hidden fields can be modified.'},
	3: {reg: '/xpath\.(compile|evaluate).*(\'|").*\+.*\+/',impact:'Xpath injection susceptibility'}
};

// GENERIC WARNIGS FOR C,PHP,PERL

var GENERIC = {
    1: {reg: '/srand\(/',impact:'Insecure seeding, not recommended for cryptographic use'},
    2: {reg: '/rand\(/',impact:'Insecure seeding, not recommended for cryptographic use'},
    3: {reg: '/getc\(/',impact:'Watch out for passed arguments'},
    4: {reg: '/readdir\(/',impact:'Watch out for passed arguments'},
    5: {reg: '/read\(/',impact:'Watch out for passed arguments'},
    6: {reg: '/sysread\(/',impact:'Watch out for passed arguments'},		
    7: {reg: '/unmask\(/',impact:'Watch out for passed arguments'},
    8: {reg: '/mkdir\(/',impact:'Watch out for passed arguments'},
    9: {reg: '/chdir\(/',impact:'Watch out for passed arguments'},
    10: {reg: '/rmdir\(/',impact:'Watch out for passed arguments'},	 	
    11: {reg: '/chmod\(/',impact:'Watch out for passed arguments'},
    12: {reg: '/link\(/',impact:'Watch out for passed arguments'},
    13: {reg: '/unlink\(/',impact:'Watch out for passed arguments'},
    14: {reg: '/symlink\(/',impact:'Watch out for passed arguments'},
    15: {reg: '/exec\(/',impact:'Dangerous system call'},
    16: {reg: '/syscall\(/',impact:'Dangerous system call'},
    17: {reg: '/connect\(/',impact:'Dangerous system call'},
    18: {reg: '/system\(/',impact:'Dangerous system call'},
    19: {reg: '/passthru\(/',impact:'Dangerous system call'},		
    20: {reg: '/open\(/',impact:'Dangerous system call'},
    21: {reg: '/unlink\(/',impact:'Dangerous system call'},
    22: {reg: '/chown\(/',impact:'Dangerous system call'},
    23: {reg: '/truncate\(/',impact:'Dangerous system call'},
    24: {reg: '/chroot\(/',impact:'Dangerous system call'},
    25: {reg: '/kill\(/',impact:'Dangerous system call'},
    26: {reg: '/eval\(/',impact:'Dangerous system call'},
    27: {reg: '/glob\(/',impact:'Dangerous system call'},
    28: {reg: '/fork\(/',impact:'Dangerous system call'},
    29: {reg: '/unset\(/',impact:'Unsetting arrays could pose a risk'},
    30: {reg: '/gethostbyname\(/',impact:'Do not trust DNS requests'},
    31: {reg: '/gethostbyaddr\(/',impact:'Do not trust DNS requests'}
};
	 
// PYTHON
var PYTHON = {	

    1: {reg: '/access\(/',impact:'Caution on system function'},
    2: {reg: '/mkfifo\(/',impact:'Caution on system function'},	 
    3: {reg: '/pathconf\(/',impact:'Caution on passed path arguments'},	
    4: {reg: '/listdir\(/',impact:'Caution on passed arguments'},	
    5: {reg: '/open\(/',impact:'Caution on passed arguments'},
    6: {reg: '/lstat\(/',impact:'Caution on system calls'},
    7: {reg: '/stat\(/',impact:'Caution on system calls'},	 
    8: {reg: '/chmod\(/',impact:'Caution on system calls and passed arguments'},	 
    9: {reg: '/chown\(/',impact:'Caution on system calls and passed arguments'},	
    10: {reg: '/rename\(/',impact:'Caution on system calls and passed arguments'},	
    11: {reg: '/mkdir\(/',impact:'Caution on system calls and passed arguments'},
    12: {reg: '/rmdir\(/',impact:'Caution on system calls and passed arguments'},	 	
    13: {reg: '/remove\(/',impact:'Caution on system calls and passed arguments'},	 	
    14: {reg: '/link\(/',impact:'Caution on system calls and passed arguments'},	 	
    15: {reg: '/unlink\(/',impact:'Caution on system calls and passed arguments'},	
    16: {reg: '/read\(/',impact:'Caution on system calls and passed arguments'},	
    17: {reg: '/recvfrom\(/',impact:'Caution on system calls and passed arguments'},		 
    18: {reg: '/recv\(/',impact:'Caution on system calls and passed arguments'},	   	 	 
    19: {reg: '/signal\(/',impact:'Caution on system calls'},	   
    20: {reg: '/fork\(/',impact:'Caution on system calls'},
    21: {reg: '/execv\(/',impact:'Caution on system calls and passed arguments'},	
    22: {reg: '/execve\(/',impact:'Caution on system calls and passed arguments'},		 
    23: {reg: '/execl\(/',impact:'Caution on system calls and passed arguments'},		 
    24: {reg: '/execle\(/',impact:'Caution on system calls and passed arguments'},	
    25: {reg: '/execlp\(/',impact:'Caution on system calls and passed arguments'},
    26: {reg: '/execvp\(/',impact:'Caution on system calls and passed arguments'},	 	
    27: {reg: '/setstate\(/',impact:'Caution on system calls and passed arguments'},
    28: {reg: '/system\(/',impact:'Caution on system calls and passed arguments'},
    29: {reg: '/popen\(/',impact:'Caution on system calls and passed arguments'},
    30: {reg: '/exec\(/',impact:'Caution on system calls and passed arguments'},
    31: {reg: '/execfile\(/',impact:'Caution on system calls and passed arguments'},
    32: {reg: '/eval\(/',impact:'Caution on system calls and passed arguments'},
    33: {reg: '/input\(/',impact:'Caution on raw obtained input'},
    34: {reg: '/compile\(/',impact:'Caution on obtained input'},
    35: {reg: '/tmpfile\(/',impact:'Caution on obtained input'},
    36: {reg: '/getlogin\(/',impact:'Caution on functions that can be forged'},
    37: {reg: '/ttyname\(/',impact:'Caution on functions that can be forged'},	 	 	 	 
    38: {reg: '/raw_input\(/',impact:'Caution on raw obtained input'},
    39: {reg: '/seed\(/',impact:'Insecure seeding, not recommended for cryptographic use'},	
    40: {reg: '/whseed\(/',impact:'Insecure seeding, not recommended for cryptographic use'},
    41: {reg: '/random\(/',impact:'Insecure seeding, not recommended for cryptographic use'},	
    42: {reg: '/randint\(/',impact:'Insecure seeding, not recommended for cryptographic use'},	
    43: {reg: '/randrange\(/',impact:'Insecure seeding, not recommended for cryptographic use'},		
    44: {reg: '/shuffle\(/',impact:'Insecure seeding, not recommended for cryptographic use'},	
    45: {reg: '/betavariate\(/',impact:'Insecure seeding, not recommended for cryptographic use'},	
    46: {reg: '/cunifvariate\(/',impact:'Insecure seeding, not recommended for cryptographic use'},		
    47: {reg: '/expovariate\(/',impact:'Insecure seeding, not recommended for cryptographic use'},
    48: {reg: '/lognormvariate\(/',impact:'Insecure seeding, not recommended for cryptographic use'},
    49: {reg: '/normalvariate\(/',impact:'Insecure seeding, not recommended for cryptographic use'},
    50: {reg: '/vonmisesvariate\(/',impact:'Insecure seeding, not recommended for cryptographic use'},
    51: {reg: '/paretovariate\(/',impact:'Insecure seeding, not recommended for cryptographic use'},
    52: {reg: '/weibullvariate\(/',impact:'Insecure seeding, not recommended for cryptographic use'},
    53: {reg: '/gamma\(/',impact:'Insecure seeding, not recommended for cryptographic use'},
    54: {reg: '/gauss\(/',impact:'Insecure seeding, not recommended for cryptographic use'},
    55: {reg: '/gethostbyname\(/',impact:'Do not trust DNS requests'},
    56: {reg: '/gethostbyaddr\(/',impact:'Do not trust DNS requests'},
    57: {reg: '/gethostbyname_ex\(/',impact:'Do not trust DNS requests'}
};		

// COLDFUSION
var COLDFUSION = {
    1: {reg: '/=\s*\t*(\'|")\s*\t*#.*#\s*\t*(\'|")/',impact:'Cfquery injection'},
    2: {reg: '/#PreserveSingleQuotes\(.*\)#/',impact:'Single quotes susceptibility'}
};

// JAVA
var JAVA = {
    1: {reg: '/System\.gc\(\)/',impact:'Explicit request for garbage collection'},
    2: {reg: '/new(.*)\(\)(.*)public(.*)run\(\)(.*){/',impact:'Call to Thread.run(), instead of start()'},
    3: {reg: '/interrupt\(/',impact:'Susceptibility on resource exhaustion inside interrupt()'},
    4: {reg: '/\.getClass\(\)\.getName\(\)\.equals\((.*)\)/',impact:'Comparing classes by name.'},
    5: {reg: '/catch(.*)\((.*)\)(.*)System\.out\.println\(/',impact:'Information leakage on debugging errors'},
    6: {reg: '/createTempFile\s*\(/',impact:'Information leakage on temp files'}	
};

// J2EE
var J2EE = {
    1: {reg: '/>\s*\${(.*)\.(.*)}\s*</',impact:'J2EE XSS susceptibility'},
    2: {reg: '/System\.exit\(/',impact:'Shut down of the application container'},	
    3: {reg: '/DriverManager\.getConnection\(/',impact:'Duplicate resource'},
    4: {reg: '/<entity>(.*)<remote>(.*)<\/remote>/',impact:'Remote entity bean'},
    5: {reg: '/<role-name>\s*ANYONE\s*<\/role-name>(.*)<ejb/',impact:'ANYONE role permission granted to EJB'}	
};

// C,C++
var CSYM = {
    1: {reg: '/strncpy\s*\((.*)\[find\((.*)\)\](.*)\)/',impact:'strncpy() find() can result in buffer underwrite'},
    2: {reg: '/scanf\s*\((.*)memcpy\(/',impact:'memcpy() with scanf() has impact destination buffers'},
    3: {reg: '/gets\s*\(/',impact:'gets() has impact on destination buffers'},
    4: {reg: '/strcpy\s*\(/',impact:'strcpy() has impact on destination buffers'},
    5: {reg: '/strcat\s*\(/',impact:'strcat() has impact on destination buffers'},
    6: {reg: '/(snprintf|printf)\((.*)argv\[/',impact:'Unchecked arguments has impact on destination buffers'},
    7: {reg: '/sscanf\(/',impact:'Unsafe function has impact on destination buffers'},    
    8: {reg: '/_sscanf_l\(/',impact:'Unsafe function has impact on destination buffers'},    
    9: {reg: '/swscanf\(/',impact:'Unsafe function has impact on destination buffers'},    
    10: {reg: '/_swscanf_l\(/',impact:'Unsafe function has impact on destination buffers'},    
    11: {reg: '/_tprintf\(/',impact:'Unsafe function has impact on destination buffers'},
    12: {reg: '/_tscanf\(/',impact:'Unsafe function has impact on destination buffers'},
    13: {reg: '/_ftprintf\(/',impact:'Unsafe function has impact on destination buffers'},
    14: {reg: '/_ftprintf\(/',impact:'Unsafe function has impact on destination buffers'},
    15: {reg: '/vprintf\(/',impact:'Unsafe function has impact on destination buffers'},
    16: {reg: '/vfprintf\(/',impact:'Unsafe function has impact on destination buffers'},
    17: {reg: '/vfwprintf\(/',impact:'Unsafe function has impact on destination buffers'},
    18: {reg: '/vswprintf\(/',impact:'Unsafe function has impact on destination buffers'},
    19: {reg: '/vswprintf\(/',impact:'Unsafe function has impact on destination buffers'},
    20: {reg: '/_vsnwprintf\(/',impact:'Unsafe function has impact on destination buffers'},
    21: {reg: '/wprintf\(/',impact:'Unsafe function has impact on destination buffers'},
    22: {reg: '/wscanf\(/',impact:'Unsafe function has impact on destination buffers'},
    23: {reg: '/fwprintf\(/',impact:'Unsafe function has impact on destination buffers'},
    24: {reg: '/_ftscanf\(/',impact:'Unsafe function has impact on destination buffers'},
    25: {reg: '/fwscanf\(/',impact:'Unsafe function has impact on destination buffers'},
    26: {reg: '/_cprintf\(/',impact:'Unsafe function has impact on destination buffers'},
    27: {reg: '/_cscanf\(/',impact:'Unsafe function has impact on destination buffers'},
    28: {reg: '/swprintf\(/',impact:'Unsafe function has impact on destination buffers'},
    29: {reg: '/_stprintf\(/',impact:'Unsafe function has impact on destination buffers'},
    30: {reg: '/_stscanf\(/',impact:'Unsafe function has impact on destination buffers'}, 
    31: {reg: '/chroot\s*\(argv\[/',impact:'Jail break'},
    32: {reg: '/chroot\s*\(/',impact:'Possible jail break susceptibility'},
    33: {reg: '/realloc\((.*)scrub_memory\(/',impact:'Possible heap inspection susceptibility'},
    34: {reg: '/rawmemchr\(argv\[/',impact:'Possible illegal pointer value susceptibility'},
    35: {reg: '/(while|for)\((.*)threadLock(.*)true/',impact:'Possible accidental threadLocking susceptibility'},
    36: {reg: '/(xmalloc|malloc)((.*)\*sizeof\((.*)\*\)/',impact:'Possible integer overflow susceptibility'},
    37: {reg: '/while\((.*)fork\(/',impact:'Possible fork resource exhaustion susceptibility inside loop'},
    38: {reg: '/switch\((.*)%[0-9]\)/',impact:'Possible race condition susceptibility on a switch'},    
    39: {reg: '/signal\((.*)\)(.*)sleep\(/',impact:'Possible race condition on signal handler'},
    40: {reg: '/char\s*\*(.*)=\s*\(\s*char\s*\*\)\s*((.*)(\+|-|\/)(.*)\)/',impact:'Possible invalid pointer scaling'},
    41: {reg: '/WinExec/',impact:'Care is advised with this function'},
    42: {reg: '/CreateProcess/',impact:'Care is advised with this function'},
    43: {reg: '/CreateProcessAsUser/',impact:'Care is advised with this function'},
    44: {reg: '/CreateProcessWithLogon/',impact:'Care is advised with this function'},
    45: {reg: '/RpcImpersonateClient/',impact:'Care is advised with this function'},
    46: {reg: '/ImpersonateLoggedOnUser/',impact:'Care is advised with this function'},
    47: {reg: '/ImpersonateNamedPipeClient/',impact:'Care is advised with this function'},
    48: {reg: '/ImpersonateDdeClientWindow/',impact:'Care is advised with this function'},
    49: {reg: '/ImpersonateSecurityContext/',impact:'Care is advised with this function'},
    50: {reg: '/InitializeCriticalSection/',impact:'Care is advised with this function'},
    51: {reg: '/EnterCriticalSection/',impact:'Care is advised with this function'},
    52: {reg: '/LoadLibraryEx/',impact:'Care is advised with this function'},
    53: {reg: '/AfxLoadLibrary/',impact:'Care is advised with this function'},
    54: {reg: '/SetSecurityDescriptorDacl/',impact:'Care is advised with this function'},
    55: {reg: '/QuerySecurityContextToken/',impact:'Care is advised with this function'},
    56: {reg: '/SetThreadToken/',impact:'Care is advised with this function'},
    57: {reg: '/tmpfile\s*\(/',impact:'Temporary files are readable and writeable'},
    58: {reg: '/getenv\(/',impact:'Possible environment variable leakage'}		
};

// .NET, ASP
var DOTNET = {
    1: {reg: '/<compilation\s*debug\s*=.*true/',impact:'It is advised to turn off debugging'},
    2: {reg: '/<customErrors\s*mode\s*=.*Off/',impact:'Misconfiguration. The current configuration returns a visible stack trace'},
    3: {reg: '/<trust\s*level\s*=\s*"(Medium|Low|Minimal)"/',impact:'Server trust level is too low.'},
    4: {reg: '/ValidateRequest\s*=.*false/',impact:'.NET Request validation is turned off, it is advised to enable it.'},
    5: {reg: '/Response\.Write\(.*Request\./',impact:' XSS susceptibility'},
    6: {reg: '/<%=[a-z]/',impact:' Possible XSS susceptibility'},
    7: {reg: '/Request\.Form/',impact:'Care must be taken on submitted form values'},
    8: {reg: '/\.Open.*=".*\s*&/',impact:' ADODB SQL Injection susceptibility'},
    9: {reg: '/(select|insert|update|union).*(where|set|in|like).*(\'|"|%|+)/',impact:'SQL Injection susceptibility'},
    10: {reg: '/Replace(.*,\s*(\\|\.\.)/',impact:'Possible logic flaw in trying to prevent directory traversal'}
};

// PHP
var PHP = {
    1: {reg: '/tmpfile\s*\(/',impact:'Temporary files are virtually readable and writeable'},
    2: {reg: '/mysql_error\(/',impact:'Information leakage on SQL errors'},
    3: {reg: '/str_replace\("\s+\'\s*",\s*"\s*\'\s*\'\s*"/',impact:'Failed to match on str_replace()'},
    4: {reg: '/(<\?=|<\?php\s*echo)\s*\$_/',impact:' Possible XSS susceptibility'},
    5: {reg: '/(select|insert|update|union|delete).*(where|set|in|like).*(\'|"|%)\s*\.\s*\$/',impact:'SQL Injection susceptibility'},
    6: {reg: '/mysql_escape_string\(/',impact:'Insecure escape function'},
    7: {reg: '/mysql_pconnect\(/',impact:'Caution on persistent connections'},
    8: {reg: '/addslashes\(/',impact:'Insecure escape function'},
    9: {reg: '/html_entity_decode\(/',impact:'Caution on using html_entity_decode which could facilitate XSS'},
    10: {reg: '/htmlspecialchars_decode\(/',impact:'Caution on using htmlspecialchars_decode which could facilitate XSS'},
    11: {reg: '/parse_str\(/',impact:'Caution on using parse_str() which could facilitate XSS or PHP injection'},
    12: {reg: '/strip_tags(\(/',impact:'Caution on using strip_tags() on allowed tags, which could facilitate XSS'},
    13: {reg: '/\$HTTP_COOKIE_VARS/',impact:'Caution on obtained user supplied data'},
    14: {reg: '/\$HTTP_GET_VARS/',impact:'Caution on obtained user supplied data'},
    15: {reg: '/\$HTTP_REQUEST_VARS/',impact:'Caution on obtained user supplied data'},
    16: {reg: '/\$HTTP_ENV_VARS/',impact:'Caution on obtained user supplied data'},
    17: {reg: '/\$HTTP_SERVER_VARS/',impact:'Caution on obtained user supplied data'},
    18: {reg: '/\$HTTP_COOKIE_VARS/',impact:'Caution on obtained user supplied data'},
    19: {reg: '/\$HTTP_SESSION_VARS/',impact:'Caution on obtained user supplied data'},
    20: {reg: '/\$_COOKIE/',impact:'Caution on obtained user supplied data'},
    21: {reg: '/\$GLOBALS/',impact:'Caution on obtained user supplied data'},
    22: {reg: '/\$_SERVER/',impact:'Caution on obtained user supplied data'},
    23: {reg: '/\$PATH_/',impact:'Caution on obtained user supplied data'},
    24: {reg: '/\$_SESSION\[/',impact:'Caution on obtained user supplied data'},
    25: {reg: '/\$_ENV\[/',impact:'Caution on obtained user supplied data'},
    26: {reg: '/\$_FILES\[/',impact:'Caution on obtained user supplied data'},
    27: {reg: '/\$_GET\[/',impact:'Caution on obtained user supplied data'},
    28: {reg: '/\$_REQUEST\[/',impact:'Caution on obtained user supplied data'},
    29: {reg: '/unset\(/',impact:'Caution on array unsetting'},
    30: {reg: '/session_/',impact:'Caution on sessions'},
    31: {reg: '/nclude\(/',impact:'Caution on including files and passed arguments'},
    32: {reg: '/require\(/',impact:'Caution on including files and passed arguments'},
    33: {reg: '/file_(.*)\(/',impact:'Caution on files and passed arguments'},
    34: {reg: '/virtual\(/',impact:'Caution on including files and passed arguments'},
    35: {reg: '/var_dump\(/',impact:'Information leakage'},
    36: {reg: '/setcookie\(/',impact:'Caution on obtained user supplied data'},
    37: {reg: '/eval\(/',impact:'Caution on system functions and passed arguments'},
    38: {reg: '/escapeshellarg\(/',impact:'Caution on system functions and passed arguments'},
    39: {reg: '/escapeshellcmd\(/',impact:'Caution on system functions and passed arguments'},
    40: {reg: '/exec\(/',impact:'Caution on system functions and passed arguments'},
    41: {reg: '/passthru\(/',impact:'Caution on system functions and passed arguments'},
    42: {reg: '/proc_close\(/',impact:'Caution on system functions and passed arguments'},
    43: {reg: '/proc_get_ status\(/',impact:'Caution on system functions and passed arguments'},
    44: {reg: '/proc_nice\(/',impact:'Caution on system functions and passed arguments'},
    45: {reg: '/proc_open\(/',impact:'Caution on system functions and passed arguments'},
    46: {reg: '/proc_terminate\(/',impact:'Caution on system functions and passed arguments'},
    47: {reg: '/shell_exec\(/',impact:'Caution on system functions and passed arguments'},
    48: {reg: '/system\(/',impact:'Caution on system functions and passed arguments'},
    49: {reg: '/ftp_/',impact:'Caution on system functions and passed arguments'},
    50: {reg: '/mail\(/',impact:'Caution on system functions and passed arguments'},
    51: {reg: '/FILEINFO_/',impact:'Caution on system functions and passed arguments'},
    52: {reg: '/basename\(/',impact:'Caution on system functions and passed arguments'},
    53: {reg: '/chgrp\(/',impact:'Caution on system functions and passed arguments'},
    54: {reg: '/chmod\(/',impact:'Caution on system functions and passed arguments'},
    55: {reg: '/chown\(/',impact:'Caution on system functions and passed arguments'},
    56: {reg: '/clearstatcache\(/',impact:'Caution on system functions and passed arguments'},
    57: {reg: '/copy\(/',impact:'Caution on system functions and passed arguments'},
    58: {reg: '/delete\(/',impact:'Caution on system functions and passed arguments'},
    59: {reg: '/dirname\(/',impact:'Caution on system functions and passed arguments'},
    60: {reg: '/disk_free_space\(/',impact:'Caution on system functions and passed arguments'},
    61: {reg: '/disk_total_space\(/',impact:'Caution on system functions and passed arguments'},
    62: {reg: '/diskfreespace\(/',impact:'Caution on system functions and passed arguments'},
    63: {reg: '/fclose\(/',impact:'Caution on system functions and passed arguments'},
    64: {reg: '/feof\(/',impact:'Caution on system functions and passed arguments'},
    65: {reg: '/fflush\(/',impact:'Caution on system functions and passed arguments'},
    66: {reg: '/fgetc\(/',impact:'Caution on system functions and passed arguments'},
    67: {reg: '/fgetcsv\(/',impact:'Caution on system functions and passed arguments'},
    68: {reg: '/fgets\(/',impact:'Caution on system functions and passed arguments'},
    69: {reg: '/fgetss\(/',impact:'Caution on system functions and passed arguments'},
    70: {reg: '/file_exists\(/',impact:'Caution on system functions and passed arguments'},
    71: {reg: '/file_get_contents\(/',impact:'Caution on system functions and passed arguments'},
    72: {reg: '/file_put_contents\(/',impact:'Caution on system functions and passed arguments'},
    73: {reg: '/file\(/',impact:'Caution on system functions and passed arguments'},
    74: {reg: '/fileatime\(/',impact:'Caution on system functions and passed arguments'},
    75: {reg: '/filectime\(/',impact:'Caution on system functions and passed arguments'},
    76: {reg: '/filegroup\(/',impact:'Caution on system functions and passed arguments'},
    77: {reg: '/fileinode\(/',impact:'Caution on system functions and passed arguments'},
    78: {reg: '/filemtime\(/',impact:'Caution on system functions and passed arguments'},
    79: {reg: '/fileowner\(/',impact:'Caution on system functions and passed arguments'},
    80: {reg: '/fileperms\(/',impact:'Caution on system functions and passed arguments'},
    81: {reg: '/filesize\(/',impact:'Caution on system functions and passed arguments'},
    82: {reg: '/filetype\(/',impact:'Caution on system functions and passed arguments'},
    83: {reg: '/flock\(/',impact:'Caution on system functions and passed arguments'},
    84: {reg: '/fnmatch\(/',impact:'Caution on system functions and passed arguments'},
    85: {reg: '/fopen\(/',impact:'Caution on system functions and passed arguments'},
    86: {reg: '/fpassthru\(/',impact:'Caution on system functions and passed arguments'},
    87: {reg: '/fputcsv\(/',impact:'Caution on system functions and passed arguments'},
    88: {reg: '/fputs\(/',impact:'Caution on system functions and passed arguments'},
    89: {reg: '/fread\(/',impact:'Caution on system functions and passed arguments'},
    90: {reg: '/fscanf\(/',impact:'Caution on system functions and passed arguments'},
    91: {reg: '/fseek\(/',impact:'Caution on system functions and passed arguments'},
    92: {reg: '/fstat\(/',impact:'Caution on system functions and passed arguments'},
    93: {reg: '/ftell\(/',impact:'Caution on system functions and passed arguments'},
    94: {reg: '/ftruncate\(/',impact:'Caution on system functions and passed arguments'},
    95: {reg: '/fwrite\(/',impact:'Caution on system functions and passed arguments'},
    96: {reg: '/glob\(/',impact:'Caution on system functions and passed arguments'},
    97: {reg: '/s_dir\(/',impact:'Caution on system functions and passed arguments'},
    98: {reg: '/s_executable\(/',impact:'Caution on system functions and passed arguments'},
    99: {reg: '/s_file\(/',impact:'Caution on system functions and passed arguments'},
    100: {reg: '/s_link\(/',impact:'Caution on system functions and passed arguments'},
    101: {reg: '/s_readable\(/',impact:'Caution on system functions and passed arguments'},
    102: {reg: '/s_uploaded_fil\(/',impact:'Caution on system functions and passed arguments'},
    103: {reg: '/s_writable\(/',impact:'Caution on system functions and passed arguments'},
    104: {reg: '/s_writeable\(/',impact:'Caution on system functions and passed arguments'},
    105: {reg: '/lchgrp\(/',impact:'Caution on system functions and passed arguments'},
    106: {reg: '/lchown\(/',impact:'Caution on system functions and passed arguments'},
    107: {reg: '/link\(/',impact:'Caution on system functions and passed arguments'},
    108: {reg: '/linkinfo\(/',impact:'Caution on system functions and passed arguments'},
    109: {reg: '/lstat\(/',impact:'Caution on system functions and passed arguments'},
    110: {reg: '/mkdir\(/',impact:'Caution on system functions and passed arguments'},
    111: {reg: '/move_uploaded_file\(/',impact:'Caution on system functions and passed arguments'},
    112: {reg: '/parse_ini_file\(/',impact:'Caution on system functions and passed arguments'},
    113: {reg: '/pathinfo\(/',impact:'Caution on system functions and passed arguments'},
    114: {reg: '/pclose\(/',impact:'Caution on system functions and passed arguments'},
    115: {reg: '/popen\(/',impact:'Caution on system functions and passed arguments'},
    116: {reg: '/readfile\(/',impact:'Caution on system functions and passed arguments'},
    117: {reg: '/readlink\(/',impact:'Caution on system functions and passed arguments'},
    118: {reg: '/realpath\(/',impact:'Caution on system functions and passed arguments'},
    119: {reg: '/rename\(/',impact:'Caution on system functions and passed arguments'},
    120: {reg: '/rewind\(/',impact:'Caution on system functions and passed arguments'},
    121: {reg: '/rmdir\(/',impact:'Caution on system functions and passed arguments'},
    122: {reg: '/set_file_buffer\(/',impact:'Caution on system functions and passed arguments'},
    123: {reg: '/stat\(/',impact:'Caution on system functions and passed arguments'},
    124: {reg: '/symlink\(/',impact:'Caution on system functions and passed arguments'},
    125: {reg: '/tempnam\(/',impact:'Caution on system functions and passed arguments'},
    126: {reg: '/tmpfile\(/',impact:'Caution on system functions and passed arguments'},
    127: {reg: '/touch\(/',impact:'Caution on system functions and passed arguments'},
    128: {reg: '/umask\(/',impact:'Caution on system functions and passed arguments'},
    129: {reg: '/unlink\(/',impact:'Caution on system functions and passed arguments'}
};

// CRYPTOGRAPHY
var CRYPTOGRAPHIC = {
    1: {reg: '/md2\(/',impact:'MD2 hashing is insecure, use at least SHA1 or even better SHA2'},
    2: {reg: '/MHASH_MD2/',impact:'MD2 constant found. MD2 is insecure, use at least SHA1 or even better SHA2'},
    3: {reg: '/md5\(/',impact:'MD5 hashing is insecure, use at least SHA1 or even better SHA2'},
    4: {reg: '/md5_file\(/',impact:'MD5 file hashing is insecure, use at least SHA1 or even better SHA2'},
    5: {reg: '/MHASH_MD5/',impact:'MD5 constant found. MD5 is insecure, use at least SHA1 or even better SHA2'},
    6: {reg: '/\s*hash\(/',impact:'Hash function found. Use at least a SHA1 or even better a SHA2 hash flag'},
    7: {reg: '/mt_rand\(/',impact:'mt_rand is good, but not recommended in strong cryptographic use'},
    8: {reg: '/CFMX_COMPAT/',impact:'CFMX_COMPAT is not recommended for cryptographic use'},
    9: {reg: '/crypt\(/',impact:'PHP crypt() uses DES and is not recommended for cryptographic use'},
    10: {reg: '/convert_uuencode\(/',impact:'PHP convert_uuencode() is not recommended for cryptographic use'},
    11: {reg: '/convert_uudecode\(/',impact:'PHP convert_uudecode() is not recommended for cryptographic use'},
    12: {reg: '/str_rot13\(/',impact:'PHP str_rot13() is not recommended for cryptographic use'},
    13: {reg: '/base64_encode\(/',impact:'Caution on using base64 encoding, it is not recommended for cryptographic use'},
    14: {reg: '/base64_decode\(/',impact:'Caution on using base64 decoding, it is not recommended for cryptographic use'},
    15: {reg: '/UUID/',impact:'Caution on generating custom unique ID\'s'},
    16: {reg: '/GUID/',impact:'Caution on generating custom unique ID\'s'},
    17: {reg: '/openssl_/',impact:'OPENSSL function'},
    18: {reg: '/mail\(/',impact:'Insecure to mail from un-encrypted channels'},
    19: {reg: '/des\(/',impact:'DES is insecure,  not recommended for cryptographic use'},
    20: {reg: '/MCRYPT_DES/',impact:'DES constant found. DES is insecure, not recommended for cryptographic use'},
    21: {reg: '/MCRYPT_3DES/',impact:'DES constant found. DES is insecure, not recommended for cryptographic use'},
    22: {reg: '/MCRYPT_CRYPT/',impact:'CRYPT constant found. CRYPT is insecure, not recommended for cryptographic use'},
    23: {reg: '/MCRYPT_RC/',impact:'RC* cipher constant found. RC is insecure, not recommended for strong cryptographic use'},
    24: {reg: '/seed\(/',impact:'Insecure seeding, not recommended for cryptographic use'},
    25: {reg: '/whseed\(/',impact:'Insecure seeding, not recommended for cryptographic use'},
    26: {reg: '/random\(/',impact:'Insecure seeding, not recommended for cryptographic use'},	
    27: {reg: '/rand\(/',impact:'Insecure seeding, not recommended for cryptographic use'},	
    28: {reg: '/srand\(/',impact:'Insecure seeding, not recommended for cryptographic use'},
    29: {reg: '/mktime\(/',impact:'Insecure seeding, not recommended for cryptographic use'},	
    30: {reg: '/time\(/',impact:'Insecure seeding, not recommended for cryptographic use'},	
    31: {reg: '/microtime\(/',impact:'Insecure seeding, not recommended for cryptographic use'},		
    32: {reg: '/randint\(/',impact:'Insecure seeding, not recommended for cryptographic use'},	
    33: {reg: '/randrange\(/',impact:'Insecure seeding, not recommended for cryptographic use'},		
    34: {reg: '/shuffle\(/',impact:'Insecure seeding, not recommended for cryptographic use'},	
    35: {reg: '/betavariate\(/',impact:'Insecure seeding, not recommended for cryptographic use'},	
    36: {reg: '/cunifvariate\(/',impact:'Insecure seeding, not recommended for cryptographic use'},		
    37: {reg: '/expovariate\(/',impact:'Insecure seeding, not recommended for cryptographic use'},
    38: {reg: '/lognormvariate\(/',impact:'Insecure seeding, not recommended for cryptographic use'},
    39: {reg: '/normalvariate\(/',impact:'Insecure seeding, not recommended for cryptographic use'},
    40: {reg: '/vonmisesvariate\(/',impact:'Insecure seeding, not recommended for cryptographic use'},
    41: {reg: '/paretovariate\(/',impact:'Insecure seeding, not recommended for cryptographic use'},
    42: {reg: '/weibullvariate\(/',impact:'Insecure seeding, not recommended for cryptographic use'},
    43: {reg: '/gamma\(/',impact:'Insecure seeding, not recommended for cryptographic use'},
    44: {reg: '/gauss\(/',impact:'Insecure seeding, not recommended for cryptographic use'}
};


var TRAVERSE = [
    'etc/passwd',
    '../etc/passwd',
    '../../etc/passwd',
    '../../../etc/passwd',
    '../../../../etc/passwd',
    '../../../../../etc/passwd',
    '../../../../../../etc/passwd',
    '../../../../../../../etc/passwd',
    '../../../../../../../../etc/passwd',
    '../../../../../../../../../etc/passwd',
    '../../../../../../../../../../etc/passwd',
    '../../../../../../../../../../../etc/passwd',
    '../../../../../../../../../../../../etc/passwd',
    '../../../../../../../../../../../../../etc/passwd',
    '../../../../../../../../../../../../../../etc/passwd',
    'etc/passwd%00',
    '../etc/passwd%00',
    '../../etc/passwd%00',
    '../../../etc/passwd%00',
    '../../../../etc/passwd%00',
    '../../../../../etc/passwd%00',
    '../../../../../../etc/passwd%00',
    '../../../../../../../etc/passwd%00',
    '../../../../../../../../etc/passwd%00',
    '../../../../../../../../../etc/passwd%00',
    '../../../../../../../../../../etc/passwd%00',
    '../../../../../../../../../../../etc/passwd%00',
    '../../../../../../../../../../../../etc/passwd%00',
    '../../../../../../../../../../../../../etc/passwd%00',
    '../../../../../../../../../../../../../../etc/passwd%00',
    '%c0%ae%c0%ae/etc/passwd',
    '%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd',
    '%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd',
    '%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd',
    '%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd',
    '%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd',
    '%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd',
    '%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd',
    '%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd',
    '%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd',
    '%2e%2e%2fetc/passwd',
    '%2e%2e%2f%2e%2e%2fetc/passwd',
    '%2e%2e%2f%2e%2e%2f%2e%2e%2fetc/passwd',
    '%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2fetc/passwd',
    '%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2fetc/passwd',
    '%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2fetc/passwd',
    '%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2fetc/passwd',
    '%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2fetc/passwd',
    '%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2fetc/passwd',
    '%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2fetc/passwd',
    '%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2fetc/passwd',
    '%2e%2e%2fetc/passwd%00',
    '%2e%2e%2f%2e%2e%2fetc/passwd%00',
    '%2e%2e%2f%2e%2e%2f%2e%2e%2fetc/passwd%00',
    '%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2fetc/passwd%00',
    '%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2fetc/passwd%00',
    '%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2fetc/passwd%00',
    '%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2fetc/passwd%00',
    '%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2fetc/passwd%00',
    '%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2fetc/passwd%00',
    '..%2fetc/passwd',
    '..%2f..%2fetc/passwd',
    '..%2f..%2f..%2fetc/passwd',
    '..%2f..%2f..%2f..%2fetc/passwd',
    '..%2f..%2f..%2f..%2f..%2fetc/passwd',
    '..%2f..%2f..%2f..%2f..%2f..%2fetc/passwd',
    '..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2fetc/passwd',
    '..%2f..%2f..%2f..%2f..%2f..%2f%..2f..%2f..%2f..%2fetc/passwd',
    '..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2fetc/passwd',
    '..%2fetc/passwd%00',
    '..%2f..%2fetc/passwd%00',
    '..%2f..%2f..%2fetc/passwd%00',
    '..%2f..%2f..%2f..%2fetc/passwd%00',
    '..%2f..%2f..%2f..%2f..%2fetc/passwd%00',
    '..%2f..%2f..%2f..%2f..%2f..%2fetc/passwd%00',
    '..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2fetc/passwd%00',
    '..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2fetc/passwd%00',
    '..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2fetc/passwd%00',
    '%2e%2e/etc/passwd',
    '%2e%2e/%2e%2e/etc/passwd',
    '%2e%2e/%2e%2e/%2e%2e/etc/passwd',
    '%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/passwd',
    '%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/passwd',
    '%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/passwd',
    '%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/passwd',
    '%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/passwd',
    '%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/passwd',
    '%2e%2e/etc/passwd%00',
    '%2e%2e/%2e%2e/etc/passwd%00',
    '%2e%2e/%2e%2e/%2e%2e/etc/passwd%00',
    '%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/passwd%00',
    '%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/passwd%00',
    '%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/passwd%00',
    '%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/passwd%00',
    '%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/passwd%00',
    '%c0%ae%c0%ae/etc/passwd',
    '%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd',
    '%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd',
    '%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd',
    '%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd',
    '%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd',
    '%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd',
    '%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd',
    '%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd',
    '%c0%ae%c0%ae/etc/passwd%00',
    '%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd%00',
    '%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd%00',
    '%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd%00',
    '%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd%00',
    '%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd%00',
    '%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd%00',
    '%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd%00',
    '%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd%00',
    '..\boot.ini',
    '..\..\boot.ini',
    '..\..\..\boot.ini',
    '..\..\..\..\boot.ini',
    '..\..\..\..\..\boot.ini',
    '..\..\..\..\..\..\boot.ini',
    '..\..\..\..\..\..\..\boot.ini',
    '..\..\..\..\..\..\..\..\boot.ini',
    '..\..\..\..\..\..\..\..\boot.ini',
    '..\..\..\..\..\..\..\..\..\boot.ini',
    '....\\....\\boot.ini ',
    '....\\....\\....\\boot.ini ',
    '....\\....\\....\\....\\boot.ini ',
    '....\\....\\....\\....\\....\\boot.ini ',
    '....\\....\\....\\....\\....\\....\\boot.ini ',
    '....\\....\\....\\....\\....\\....\\....\\boot.ini ',
    '....\\....\\....\\....\\....\\....\\....\\....\\boot.ini ',
    '....\\....\\....\\....\\....\\....\\....\\....\\....\\boot.ini ',
    '....\\....\\....\\....\\....\\....\\....\\....\\....\\....\\boot.ini ',
    '....//....//boot.ini',
    '....//....//....//boot.ini',
    '....//....//....//....//boot.ini',
    '....//....//....//....//....//boot.ini',
    '....//....//....//....//....//....//boot.ini',
    '....//....//....//....//....//....//....//boot.ini',
    '....//....//....//....//....//....//....//....//boot.ini',
    '....//....//....//....//....//....//....//....//....//boot.ini',

    '....//....//....//....//....//....//....//....//....//....//boot.ini',
    '%2e%2e\%2e%2e\boot.ini',
    '%2e%2e\%2e%2e\%2e%2e\boot.ini',
    '%2e%2e\%2e%2e\%2e%2e\%2e%2e\boot.ini',
    '%2e%2e\%2e%2e\%2e%2e\%2e%2e\%2e%2e\boot.ini',
    '%2e%2e\%2e%2e\%2e%2e\%2e%2e\%2e%2e\%2e%2e\boot.ini',
    '%2e%2e\%2e%2e\%2e%2e\%2e%2e\%2e%2e\%2e%2e\%2e%2e\boot.ini',
    '%2e%2e%5c%2e%2e%5cboot.ini ',
    '%2e%2e%5c%2e%2e%5c%2e%2e%5cboot.ini ',
    '%2e%2e%5c%2e%2e%5c%2e%2e%5c%2e%2e%5cboot.ini ',
    '%2e%2e%5c%2e%2e%5c%2e%2e%5c%2e%2e%5c%2e%2e%5cboot.ini ',
    '%2e%2e%5c%2e%2e%5c%2e%2e%5c%2e%2e%5c%2e%2e%5c%2e%2e%5cboot.ini ',
    '%2e%2e%5c%2e%2e%5c%2e%2e%5c%2e%2e%5c%2e%2e%5c%2e%2e%5c%2e%2e%5cboot.ini ',
    '%2e%2e%5c%2e%2e%5c%2e%2e%5c%2e%2e%5c%2e%2e%5c%2e%2e%5c%2e%2e%5c%2e%2e%5cboot.ini ',
    '%2e%2e%5c%2e%2e%5c%2e%2e%5c%2e%2e%5c%2e%2e%5c%2e%2e%5c%2e%2e%5c%2e%2e%5c%2e%2e%5cboot.ini ',
    '..%c0%af..%c0%afboot.ini',
    '..%c0%af..%c0%af..%c0%afboot.ini',
    '..%c0%af..%c0%af..%c0%af..%c0%afboot.ini',
    '..%c0%af..%c0%af..%c0%af..%c0%af..%c0%afboot.ini',
    '..%c0%af..%c0%af..%c0%af..%c0%af..%c0%af..%c0%afboot.ini',
    '..%c0%af..%c0%af..%c0%af..%c0%af..%c0%af..%c0%af..%c0%afboot.ini',
    '..%c1%9c..%c1%9cboot.ini',
    '..%c1%9c..%c1%9c..%c1%9cboot.ini',
    '..%c1%9c..%c1%9c..%c1%9c..%c1%9cboot.ini',
    '..%c1%9c..%c1%9c..%c1%9c..%c1%9c..%c1%9cboot.ini',
    '..%c1%9c..%c1%9c..%c1%9c..%c1%9c..%c1%9c..%c1%9cboot.ini',
    '..%c1%9c..%c1%9c..%c1%9c..%c1%9c..%c1%9c..%c1%9c..%c1%9cboot.ini'];

var SQLERRORS = [
	"Unclosed quotation mark",
	"Column count doesn't match value",
	"divison by 0",
	"Divide by zero",
	"Incorrect table name",
	"Unknown column",
	"Invalid length parameter passed",
	"operator does not exist",
	"error converting the",
	"value to a column of data type int",
	"must be quoted with",
	"Can't find any matching row",
	"Invalid use of group function",
	"Incorrect parameters to procedure",
	"Incorrect parameter count to procedure",
	"You must have privileges to update tables",
	"Can't initialize function",
	"Cross dependency found",
	"Thread stack overrun:",
	"Too many columns",
	"A table must have at least 1 column",
	"Unknown character set:",
	"Unable to cast",
	"Incorrect syntax near",
	"Warning:",
	"You have an error in your SQL syntax",
	"too many arguments on function",
	"too many columns in result set",
	"too many terms",
	"does not match any column in the result set",
	"clause should come after",
	"do not have the same number of result columns",
	"too many terms in compound",
	"ODBC SQL Server Driver",
	"ODBC SQL Server Driver",
	"ODBC Microsoft Access Driver",
	"OLE DB Provider"];



var NICS = ['biz','com','us','coop','info','name','net','gov','edu','mil','int','ac','ae','at','au','be','bg','br','bz','ca','cc','ch','cl','cn','cz','de','fr','hu','ie','il','in','ir','mc','to','tv','ru','org','aero','nl'];

var NICSERV = ['whois.neulevel.biz','whois.internic.net','whois.nic.us','whois.nic.coop','whois.nic.info','whois.nic.name','whois.internic.net','whois.nic.gov','whois.internic.net','rs.internic.net','whois.iana.org','whois.nic.ac','whois.uaenic.ae','whois.ripe.net','whois.aunic.net','whois.dns.be','whois.ripe.net','whois.registro.br','whois.belizenic.bz','whois.cira.ca','whois.nic.cc','whois.nic.ch','whois.nic.cl','whois.cnnic.net.cn','whois.nic.cz','whois.nic.de','whois.nic.fr','whois.nic.hu','whois.domainregistry.ie','whois.isoc.org.il','whois.ncst.ernet.in','whois.nic.ir','whois.ripe.net','whois.tonic.to','whois.tv','whois.ripn.net','whois.pir.org','whois.information.aero','whois.domain-registry.nl'];
	
var records = ['mail','www','ftp','ssl','https','www1','www2','mirror','database','phpmyadmin','scrape','scraper','proxy1','proxy2','proxy3','proxy4','proxy5','proxy6','proxy7','proxy8','proxy9','proxy10','proxy11','proxy12','bsd1','bsd2','bsd3','bsd4','bsd5','bsd6','mysql1','mysql2','mysql3','mysql4','mysql5','mysql6','mysql7','mysql8','usenet','config','httpt','ssh','hidden','web','docs','pub','home','jobs','careers','my','public','pub','ir','investor','investors','images','img','img01','img02','include','media','static','cdn','akamai','ssl','ssl1','ssl01','cache','video','videos','footage','ajax','xml','mobile','wap','sms','isync','cgi','members','login','signin','signup','online','tcl','apache','iis','zeus','websphere','domino','search','download','downloads','news','support','forum','forums','about','help','helpdesk','en','us','uk','de','internal','intl','intranet','www-int','int','corp','mgmt','management','sales','marketing','billing','it','eng','eng1','eng01','engineering','ops','ops1','ops01','ops2','ops02','operations','dev','dev1','dev01','warez','stage','staging','development','pr','test','lab','labs','qa','employees','go','start','tool','tools','problemtracker','tracker','bug','bugs','bugzilla','subversion','sv','svn','cvs','rcs','dhcp','ups','irc','cam','talk','chat','voip','homebase','call','ms','owa','owa01','outlook','webmail','email','strongmail','antivirus','av','spam','smtp','pop','hr','humanresources','sharepoint','blog','blogs','wordpress','drupal','rss','cms','wiki','vantive','db','db1','db01','db2','db02','mysql','mysql12','mysql01','sql','sql1','sql01','mssql','mssql2','mssql01','ldap','oracle','peoplesoft','siebel','crm','erp','customer','customers','dns','nameserv','a.auth-ns','b.auth-ns','c.auth-ns','ix','mx','mtu','mta','ns','ns1','ns01','ns2','ns02','ns3','ns4','ns5','rtr','rtr1','rtr01','att','mci','sprint','router','core','proxy','r1','r01','r2','r02','core01','sw','sw1','s1','s2','sw01','cisco','juniper','f5','lb','squid','checkpoint','foundry','wireless','ap','wlan','lan','nokia','netgear','netscreen','arcsight','citrix','vnc','netscaler','toplayer','opsware','ops','netapp','app','app1','app01','nms','nas','san','esm','ism','tivoli','openview','ov','hpov','cricket','flow','mrtg','log','log1','log01','log2','log02','logs','syslog','syslogs','ias','webstats','analyzer','xlogan','logfile','logfiles','webalizer','alterwind','activestat','clicktrack','webtrends','faststats','urchin','z-log','zlog','wusage','keynote','stat','stats','remstats','monitoring','splunk','vpn','vpn1','vpn01','vpn2','vpn02','connect','outside','inside','snort','ids','cims','sim','fs','gw','concentrator','con','console','honeypot','ad','mom','id','sec','securid','fwsm','fwsm1','fwsm01','fw','fw1','dialup','dmz','sun','sun1','sun01','sun2','sun02','bsd','freebsd','freebsd1','freebsd01','freebsd2','freebsd02','linux','linux1','linux01','linux2','linux02','win','win1','win01','win2','win02','windows','windows1','windows01','windows2','windows02','quake','counterstrike','halflife','mp3','torrent','webcam','uploads','wizard','phpmyadmin','adminscreen'];

var directories = ['nl','en','be','uk','_','__','___','@','01','02','03','0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','t','u','v','w','x','y','z','admin','administrator','phpmyadmin','database','mirror','config','db','database','proxy','dev','mp3','images','download','downloads','webcam','vpn','files','frontpage','ftp','stats','webstats','bin','plesk-stat','intranet','backup','backups','mysql','sql','data','csv','msn','webmail','old','doc','vmware','netware','novell','mambo','joomla','cms','phpnuke','squirellmail','mail','auth','webadmin','groupwise','portal','remote','admin_','default','register','_vti_cnf','_vti','maildir','private','winnt','ws_ftp','desktop','wap','share','torrent','torrents','webalizer','bash_history','shell','polly','ensim','.cobalt','bash','gateway','terminal','nt','xp','lan','wan','eth0','spam','smtp','hr','resources','sharepoint','oracle','peoplesoft','siebel','crm','erp','customer','customers','squid','checkpoint','foundry','wireless','outside','inside','snort','outlook','lotus','voip','aa','aaa','aaaa','bb','bbb','bbbb','cc','ccc','cccc','dd','ddd','dddd','001','0001','00001','11','111','1111','_1','_11','area51','_area51','UFO','confidential','007','777','classified','mediafiles','backup','_backup','backups','plugins','plug','uni','photoshop','dreamweaver','flash','swf','fla','mark','john','mary','susan','ann','anne','robert','bill','tom','myfiles','mydownloads','myuploads','newtorents','movies','video','pager','allusers','databases','db1','db2','db3','db01','db02','db03','musicfiles','wmv','porn','girls','camserver','javaserver','trial','warez','0day','night','love','sex','letters','documents','lists','intra','corporate','corp','shares','stocks','stock','stockphoto','getty','designs','psd','psds','gifs','img','oscommerce','hacks','hacked','hacker','cracker','crackers','1337','leet','phorum','phpbb','bbcode','phpboard','ebay','e-bay','bay','powerseller','seller','zero','one','two','zeroday','spider','spidered','spiders','ai','x1','x2','x0','neo','matrix','quake','doom','devil','bsd','tracker','urchin','google','torch','dev1','dev1','stager','stage','stage1','prelive','live','server1','server2','backupserver','serverbackup','classes','java','oop','OoO','xy','xx','xxx','xxxx','xxxxx','xxxxxx','xxxxxxx','xxxxxxxx','xxxxxxxxx','xxxxxxxxxx','null','devlnull','bhistory','wikipedia','wiki','pre_','_pre','_db','_database','_old','_stored','_bak','personal','_personal','.svn','svn','_pers','pers','write','country','lookup','scripts','googleearth','truncate','possix','filehunter','dll','make','makefile','p2p','spamcop'];

var files = ['dat','index','list','log','logs','back','remote','users','table','database','sql','data','robots','config','db','mysql','backup','login','shop','store','web','install','installer','sys','ftp','vpn','server','demo','servlet','sendmail','mod','upload','uploads','auth','configuration','ttawlogin','login','sign','perform','clients','isapi','remote','register','delete','del','desktop','private','winnt','ws_ftp','eudora','','slapd','sites','client','wand','sysprep','htpasswd','htgroup','secring','passlist','passes','pw','trillian','master','shell','cobalt','a','ensim','agent','polly','vb','mainframe','nodes','tor','exec','default','pgp','crypt','help','terminal','1'];

var ex = ['.dat','.phps','.php~','.php','.reg','.txt','.bak','.bak~','.php.bak','.db','.rdf','.pl','.cgi','.class','.sql','.sh','.bat','.exe','.dll','.mdb','.xls','.doc','.bin','.zip','.tar.gz','.inc','.ini','.conf','.pcf','.xls','.pwd','.inf','.pgp','.skr','.asa','.batch','.cron','.ica','.cfg','.tpl'];